name='张三'
age=20
print(type(name),type(age))
print('我叫'+name+'，'+'今年'+str(age)+'岁')
s1='128.98'
s2='76'
s3='hello'
i=98
print(type(s1),type(s2),type(s3),type(i))
print(float(s1),type(float(s1)))
print(float(i),type(float(i)))